# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 759aa173f1375efe612a512283e70549b9df137c2bb3cd58023b33cf741cae909c5f5b4a8544f3726f1fe7c26c8c20483f42ad89fef4c1d35746e5eacda4d069

test:
  secret_key_base: 4c5b2640a8ddd216c25b55fdc6cb629ac43343881d18ffe3c5db0f6b10b0eca701e47913689c8165b335373878a87ba78604a4351a7337f203dc9f67f746c63b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
